# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 17:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doginformation', '0002_auto_20170621_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccinationFor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('routine', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VaccinationRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veternarian', models.CharField(max_length=100)),
                ('next_vaccine', models.CharField(max_length=100)),
                ('date_record', models.DateField(default=datetime.date.today)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dogvaccine', to='doginformation.Dog')),
                ('vaccine_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinationrecord', to='vaccination.VaccinationFor')),
            ],
        ),
    ]
