# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 17:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userinformation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('blood_type', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=2)),
                ('breed', models.CharField(max_length=100)),
                ('current_weight', models.PositiveIntegerField()),
                ('age', models.PositiveSmallIntegerField()),
                ('birth_day', models.DateField(default=datetime.date.today)),
                ('is_sterize', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('gender', models.CharField(max_length=10)),
                ('micro_no', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('timeupdate', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dog', to='userinformation.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='DogPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image/%Y/%m/')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('timeupdate', models.DateTimeField(auto_now=True)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dogpicture', to='doginformation.Dog')),
            ],
        ),
    ]
