# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 14:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userinformation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('blood_type', models.CharField(max_length=20)),
                ('breed', models.CharField(max_length=100)),
                ('current_weight', models.PositiveSmallIntegerField()),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('birth_day', models.DateField(default=datetime.date.today)),
                ('is_sterize', models.BooleanField(choices=[(True, b'Yes'), (False, b'No')])),
                ('gender', models.PositiveSmallIntegerField(choices=[(1, b'Male'), (2, b'Female')])),
                ('micro_no', models.CharField(blank=True, max_length=100, null=True)),
                ('color_primary', models.CharField(blank=True, max_length=20, null=True)),
                ('color_secondary', models.CharField(blank=True, max_length=20, null=True)),
                ('location', models.TextField(max_length=300)),
                ('dominance', models.CharField(max_length=200)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, b'Alive'), (2, b'Death')])),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('timeupdate', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dog', to='userinformation.Profile')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DogPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=b'image/%Y/%m/')),
                ('vector', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('timeupdate', models.DateTimeField(auto_now=True)),
                ('dog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dogpicture', to='doginformation.Dog')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
