# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doginformation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='blood_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='dog',
            name='current_weight',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='dog',
            name='gender',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Male'), (2, 'Female')]),
        ),
        migrations.AlterField(
            model_name='dog',
            name='micro_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
