# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 15:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veterinarian', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='dog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_dog', to='doginformation.Dog'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_hospital', to='veterinarian.Hospital'),
        ),
        migrations.AlterField(
            model_name='vethos',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hos', to='veterinarian.Hospital'),
        ),
        migrations.AlterField(
            model_name='vethos',
            name='vetarinarian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vet', to='veterinarian.Vetarinarian'),
        ),
    ]
