# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 16:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veterinarian', '0002_appointment_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='key',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='vethos',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veterinarian.Hospital'),
        ),
    ]
