# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finddog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='vector',
            field=models.TextField(blank=True, null=True),
        ),
    ]
