# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 17:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doginformation', '0002_auto_20170621_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='AntiParasitics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_dose', models.CharField(max_length=100)),
                ('date_record', models.DateField(default=datetime.date.today)),
                ('veterinarian', models.CharField(max_length=100)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antiparasitics', to='doginformation.Dog')),
            ],
        ),
        migrations.CreateModel(
            name='Therapy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('routine', models.CharField(max_length=200)),
                ('antiparasitics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='therapy', to='antiparasitics.AntiParasitics')),
            ],
        ),
    ]
