# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-06 18:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doginformation', '0001_initial'),
        ('antiparasitics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='antiparasitics',
            name='dog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doginformation.Dog'),
        ),
    ]
